### ISSUE TITLE
Data assembly error: Please change the -fc or -sd option.

### ISSUE THREAD

**Issue by tttxd** [bichangwei/PMAT#17]

**Comment by dnawhisperer** [comment]
Hello, was this problem solved? I also get the same error. I tried fuse-overlayfs and e2fsprogs to fix the fuse2fs problem but no luck.

What -fc or -sd settings should be changed? Thanks

**Comment by bichangwei** [comment]
We recommend that you use the latest version of our PMAT (https://github.com/aiPGAB/PMAT2) and modify the -F parameter to reduce the amount of data used for assembly.
