### ISSUE TITLE
question about error for using apptainer

### ISSUE THREAD

**Issue by cutykaka** [bichangwei/PMAT#23]
Hello. 
I've tried to use PMAT for mitochondria DNA assembly .
However, when I conducted the basic command for autoMito, I got the same error as below.

FileNotFoundError: [Errno 2] No such file or directory: 'apptainer'
[47023] Failed to execute script 'PMAT' due to unhandled exception!

But, I already installed apptainer using conda. 
What's the problem for this? Should I need to install apptainer locally or any idea to solve this problem?

Thanks.

**Comment by bichangwei** [comment]
Hello, the encountered error stems from the fact that Apptainer is not installed as a root application. To resolve this, kindly request an administrator to install it for you.

**Comment by cutykaka** [comment]
Thank you! solved!
