### ISSUE TITLE
Coverage used in Table1

### ISSUE THREAD

**Issue by Wenfei-Xian** [bichangwei/PMAT#8]
Hi Changewei,

Thank you for your work on the assembly of the mitochondrial genome! 
I would like to know what coverage was used for Arabidopsis thaliana in your paper.
In Table 1, there is 191.31X coverage of A. thaliana HiFi data. 
Did you use all of it for PMAT?

best,
Wenfei

**Comment by bichangwei** [comment]
Thank you for using PMAT！We only extracted 1G and 2G reads of Arabidopsis thaliana for mitogenome assembly～

If you have other questions，please join our WeChat group!

Best，

Changwei

---- Replied Message ----
| From | Wenfei ***@***.***> |
| Date | 02/11/2024 19:06 |
| To | bichangwei/PMAT ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [bichangwei/PMAT] Coverage used in Table1 (Issue #8) |

Hi Changewei,

Thank you for your work on the assembly of the mitochondrial genome!
I would like to know what coverage was used for Arabidopsis thaliana in your paper.
In Table 1, there is 191.31X coverage of A. thaliana HiFi data.
Did you use all of it for PMAT?

best,
Wenfei

**Comment by Wenfei-Xian** [comment]
What's the fair coverage for assembling chloroplast and mitochondrial genomes of other plant species using PMAT?
20X ?

Great! Please send me the QR code for the WeChat group. :)

However, it would be beneficial if we could post the issues on GitHub. This would help other users who might encounter the same problems.

Best,
Wenfei

**Comment by Wenfei-Xian** [comment]
It takes long time when the coverave is 15X in the large genome ...

```
By evaluating the assembly of plant mitogenomes from different sequencing data, it was confirmed that PMAT only requires 1× HiFi sequencing data to obtain a complete plant mitogenome
```
So I try to use 2X...
